import 'dotenv/config';

const {
  PROD_DATABASE_USER,
  PROD_DATABASE_PASSWORD,
  PROD_DATABASE_HOST,
  PROD_DATABASE_NAME,
  PROD_DATABASE_PORT,
  PROD_DATABASE_MAX_CONNECTIONS,
  DEBUG,
  PROD_PAPERTRAIL_PORT,
  PROD_PAPERTRAIL_HOST,
} = process.env;

export default {
  NODE_ENV: 'production',
  DEBUG,
  DATABASE_USER: PROD_DATABASE_USER,
  DATABASE_PASSWORD: PROD_DATABASE_PASSWORD,
  DATABASE_HOST: PROD_DATABASE_HOST,
  DATABASE_NAME: PROD_DATABASE_NAME,
  DATABASE_PORT: PROD_DATABASE_PORT,
  DATABASE_MAX_CONNECTIONS: PROD_DATABASE_MAX_CONNECTIONS,
  PAPERTRAIL_PORT: PROD_PAPERTRAIL_PORT,
  PAPERTRAIL_HOST: PROD_PAPERTRAIL_HOST,
};
