import 'dotenv/config';

const {
  STAGING_DATABASE_USER,
  STAGING_DATABASE_PASSWORD,
  STAGING_DATABASE_HOST,
  STAGING_DATABASE_NAME,
  STAGING_DATABASE_PORT,
  STAGING_DATABASE_MAX_CONNECTIONS,
  DEBUG,
  STAGING_PAPERTRAIL_PORT,
  STAGING_PAPERTRAIL_HOST,
} = process.env;

export default {
  NODE_ENV: 'staging',
  DEBUG,
  DATABASE_USER: STAGING_DATABASE_USER,
  DATABASE_PASSWORD: STAGING_DATABASE_PASSWORD,
  DATABASE_HOST: STAGING_DATABASE_HOST,
  DATABASE_NAME: STAGING_DATABASE_NAME,
  DATABASE_PORT: STAGING_DATABASE_PORT,
  DATABASE_MAX_CONNECTIONS: STAGING_DATABASE_MAX_CONNECTIONS,
  PAPERTRAIL_PORT: STAGING_PAPERTRAIL_PORT,
  PAPERTRAIL_HOST: STAGING_PAPERTRAIL_HOST,
};
